name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_platform_widgets: ^0.32.5
  cloud_firestore: ^0.13.5
  firebase_analytics: ^5.0.11
  platform_maps_flutter: ^0.1.7
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+1
  intl: ^0.16.1
  geolocator: ^5.3.2+2
  tflite: ^1.0.6
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - tensorflow/dict.txt
    - tensorflow/manifest.json
    - tensorflow/model.tflite